Semantic metadata
thingful/testharness pull request #10
Opened 2017-07-10 16:30 UTC by dotmancando

## Update TestHarness to thingfulx version semantic-metadata
Changes include:
* Generally change "fetcher" to indexer"
* Remove `Provider()`, use `UID()` instead
* Clear separation of `Fetch()` and `Parse()`, although we don't separately run them in `testharness` yet

2017-07-10 16:57 UTC, Popcore commented on testharness.go
>  			fmt.Printf("## ERROR from Fetch: %s\n", err.Error())
This should say "ERROR from Parse"

2017-07-10 16:58 UTC, Popcore commented on testharness.go
>  			fmt.Printf("## ERROR from Fetch: %s\n", err.Error())
This should say "ERROR from Parse" too

2017-07-10 16:59 UTC, Popcore commented on testharness.go
>  			fmt.Printf("## ERROR from Fetch: %s\n", err.Error())
This should say "ERROR from Parse" too

2017-07-11 13:21 UTC, smulube commented
maybe consider running gometalinter on the code - bunch of little tweaks it will recommend i think, no errors but almost certainly a few changes to make this more idiomatic (god i'm starting to hate that word ;)

2017-07-11 15:55 UTC, smulube requested changes
see my comment @dotmancando, oh and @Popcore's

2017-08-02 10:15 UTC, smulube approved these changes

2017-08-02 10:16 UTC, dotmancando commented on testharness.go
>  		// panic(err)
remove

2017-08-02 10:35 UTC, smulube commented on glide.yaml
> +  version: 0.2.0
is this the correct version?

2017-08-02 10:38 UTC, smulube commented on glide.yaml
> +  version: 0.2.0
glide does have concept of patch ranges, so you could change this to:

```
version: ~0.2.0
```

which is the same as: `>= 0.2.0` && `< 0.3.0`

2017-08-02 10:54 UTC, merged